logging:
  level:
    root: info
    org.dotwebstack: DEBUG

server:
  port: 8084

management:
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8085

dotwebstack:
  baseUrl: ${BASE_URL:http://localhost:${server.port}}
  orchestrate:
    root: proxy
    subschemas:
      proxy:
        endpoint: ${LOOKUP_API_URL:http://localhost:8080/graphql}
  openapi:
    cors:
      enabled: true
